repos:
  - repo: local
    hooks:
      - id: format-frontend
        name: Format frontend
        entry: npx --prefix frontend prettier --write --ignore-unknown
        language: system
        files: ^frontend/

      - id: format-backend-functions
        name: Format backend functions
        entry: npx --prefix backend/functions prettier --write --ignore-unknown
        language: system
        files: ^backend/functions/

      - id: check-staged-diff
        name: Check staged diff
        entry: git diff --staged --check
        language: system
        pass_filenames: false
