packages:
  - 'frontend'
  - 'backend/functions'
  - 'shared'
catalog:
  zod: 4.4.3
allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
overrides:
  'vite>esbuild': 0.28.1
  'vite>tsx': 4.22.4
